Feature/Fix-Permits-Not-Being-ETL'd
bcgov/mds pull request #1438
Opened 2020-09-03 21:05 UTC by nayr974

2020-09-03 21:11 UTC, mmumby approved these changes

2020-09-04 14:32 UTC, pdittaro approved these changes
Thanks for the fix

2020-09-04 14:42 UTC, pdittaro requested changes
Actually, this will do a weird side effect if we build out a new environment from scratch. I think its alright if we just get rid of that migration and then add the column as part of the stored procedure.

2020-09-04 16:33 UTC, Jsyro commented on migrations/sql/V2020.09.03.14.10__etl_permit_security_adjustment.sql
> -ADD COLUMN IF NOT EXISTS security_adjustment numeric;
Migration got removed?

2020-09-04 16:42 UTC, pdittaro commented on migrations/sql/V2020.09.03.14.10__etl_permit_security_adjustment.sql
> -ADD COLUMN IF NOT EXISTS security_adjustment numeric;
Yep

2020-09-04 16:42 UTC, pdittaro commented on migrations/sql/V2020.09.03.14.10__etl_permit_security_adjustment.sql
> -ADD COLUMN IF NOT EXISTS security_adjustment numeric;
It hasn't run in Dev/Test/Prod

2020-09-04 16:54 UTC, pdittaro approved these changes

2020-09-04 16:54 UTC, merged