MDS-2140 GenTax Export + Update NoW is_historical logic
bcgov/mds pull request #1589
Opened 2020-12-18 19:57 UTC by nayr974

2020-12-18 21:22 UTC, exzizt commented on services/core-api/app/api/exports/mines/resources/mine_summary_resource.py
> +    #@requires_role_view_all
Needed?

2020-12-18 21:23 UTC, exzizt commented on services/core-api/app/api/exports/mines/resources/mine_summary_resource.py
> +        json_string = None   #cache.get(MINE_DETAILS_JSON)
Re-enable?

2020-12-18 21:23 UTC, exzizt requested changes
What the heck **_IS THIS_**?!

2020-12-18 21:26 UTC, nayr974 commented on services/core-api/app/api/exports/mines/resources/mine_summary_resource.py
> +        json_string = None   #cache.get(MINE_DETAILS_JSON)
Re-enabled :)

2020-12-18 21:26 UTC, nayr974 commented on services/core-api/app/api/exports/mines/resources/mine_summary_resource.py
> +    #@requires_role_view_all
Yes, added :)

2020-12-18 21:31 UTC, exzizt submitted a review, later dismissed

2020-12-21 17:28 UTC, mhuseinov approved these changes

2021-01-04 21:26 UTC, exzizt commented on migrations/sql/R__view_mine_summary.sql
> +    efs.description AS mine_exemption_fee_status_d,
"mine_exemption_fee_status_d"? Why not "mine_exemption_fee_status_description"?

2021-01-04 21:27 UTC, exzizt approved these changes
✔️

2021-01-04 22:40 UTC, merged