adding 'is not None' condition to skip none values
bcgov/mds pull request #1854
Opened 2021-08-30 20:10 UTC by dragancolic-bcgov

# Main

- What did you focus on in this PR?
- Keep all headers and just leave a single list item 'N/A' if there's no content for that header, otherwise remove N/A and add your details!

# Other

- What other side fixes, tweaks did you add on the side?
- N/A

# How to test

- N/A

# Notes

- Any notes/screenshots for this PR?
- N/A

2021-08-30 20:22 UTC, mmumby approved these changes, later dismissed
tested - well done! 🚢 -it

2021-08-31 18:15 UTC, exzizt requested changes
This breaks the sorting logic, it will now sort by final_package_order not being None, when it should be sorting by the integer value (excluding null values, I suppose, although it should never happen where a FAP document doesn't have its final_package_order set).

2021-08-31 18:17 UTC, exzizt commented
> # Main
> * What did you focus on in this PR?
> * Keep all headers and just leave a single list item 'N/A' if there's no content for that header, otherwise remove N/A and add your details!
> 
> # Other
> * What other side fixes, tweaks did you add on the side?
> * N/A
> 
> # How to test
> * N/A
> 
> # Notes
> * Any notes/screenshots for this PR?
> * N/A

You forgot to fill out the template 😛

2021-08-31 22:19 UTC, exzizt approved these changes

2021-08-31 22:21 UTC, merged