Mds 3942 minespace submit incident notification
bcgov/mds pull request #1873
Opened 2021-10-07 00:28 UTC by areyeslo

# Main

- Provide the functionality to create new incidents on minespace. (The button to record a new incident has to be hidden when the code review will be done)

# Other
- Changes in styling were added on antd-overrides.scss and webpack.parts.js

# How to test
- Click on ![image](https://user-images.githubusercontent.com/10526131/136301250-37b5719b-9a15-4683-8fe2-4b76320184d5.png)
- Fill the required fields on the first-step form and click on Next: 
![image](https://user-images.githubusercontent.com/10526131/136589472-4f5f3344-c4db-42fd-88d7-8abb64ce2a77.png)
- Fill the required fields on the second-step form:  
![image](https://user-images.githubusercontent.com/10526131/136589620-4a23ac2d-0ddb-4c17-bd86-64d915905630.png)
- At the bottom of the form appears an alert with a legend to check understanding of contacting an inspector:
![image](https://user-images.githubusercontent.com/10526131/136589860-e52214a9-d980-42eb-9e69-e34379ff1d52.png)
- When the user clicks on the checkbox, then the Submit button is enabled to create the new incident. 
![image](https://user-images.githubusercontent.com/10526131/136590037-cc528787-09e1-4cf0-9a8c-9591e2864890.png)
- The newly created incident is added at the top of the Incidents table:
![image](https://user-images.githubusercontent.com/10526131/136590155-4a50e224-d20d-4398-b0f4-83aaf605fbf5.png)

- Email notification example:
![image](https://user-images.githubusercontent.com/10526131/136969271-8672d182-f9df-4cae-b1ae-a0263c3dc9fc.png)

# Notes
https://bcmines.atlassian.net/browse/MDS-3942

2021-10-07 18:13 UTC, mmumby commented on services/core-api/app/api/constants.py
This should be: mineincidents@gov.bc.ca

2021-10-07 18:28 UTC, mmumby commented on services/core-api/app/api/incidents/models/mine_incident.py
> +        body = f'<p>{self.mine_table.mine_name} (Mine no: {self.mine_table.mine_no}) has reported an incident in MineSpace.</p>'
Let's include the incident type to the email as well. (above the "Incident information" )

2021-10-07 18:33 UTC, mmumby commented on services/core-api/app/api/mines/incidents/resources/mine_incidents.py
> +                incident.send_incidents_email()
We'll have to use this check more throughout this API. Ie, proponents can only update specific fields, so we'll have to add more validation to the fields they cannot alter.

2021-10-07 18:34 UTC, mmumby commented on services/minespace-web/src/components/Forms/incidents/AddIncidentDetailForm.js
> +  render() {
Can you convert this to a stateless component?

2021-10-07 18:59 UTC, mmumby commented on services/minespace-web/src/components/dashboard/mine/incidents/Incidents.js
> +      this.props.fetchIncidents({
Can you move the logic for "fetchIncidents" into a common method that both the 'componentDidmount' and this method can call? 

It also appears to be missing the loading state logic here.

2021-10-07 19:01 UTC, mmumby commented on services/minespace-web/src/constants/API.js
> +// Incidents
These should already exist in the common folders.

2021-10-07 19:03 UTC, mmumby requested changes
Nice work, just a few small changes, and I'd like to see snapshot tests for all the new components.

2021-10-08 16:06 UTC, areyeslo commented on services/core-api/app/api/constants.py
Changed. Thanks for the email.

2021-10-08 16:06 UTC, areyeslo commented on services/core-api/app/api/incidents/models/mine_incident.py
> +        body = f'<p>{self.mine_table.mine_name} (Mine no: {self.mine_table.mine_no}) has reported an incident in MineSpace.</p>'
Added. Thanks for adding this detail.

2021-10-08 16:07 UTC, areyeslo commented on services/minespace-web/src/components/Forms/incidents/AddIncidentDetailForm.js
> +  render() {
Converted :)

2021-10-08 16:07 UTC, areyeslo commented on services/minespace-web/src/components/dashboard/mine/incidents/Incidents.js
> +      this.props.fetchIncidents({
Moved to common method.

2021-10-08 16:07 UTC, areyeslo commented on services/minespace-web/src/constants/API.js
> +// Incidents
They exist in common folder. Deleted from here.

2021-10-08 22:08 UTC, mmumby commented on services/core-api/app/api/incidents/models/mine_incident.py
> +        body = f'<p>{self.mine_table.mine_name} (Mine no: {self.mine_table.mine_no}) has reported an incident in MineSpace.</p>'
'categories' is an array, you will have to map through and list the descriptions here.

2021-10-12 14:21 UTC, areyeslo commented on services/core-api/app/api/incidents/models/mine_incident.py
> +        body = f'<p>{self.mine_table.mine_name} (Mine no: {self.mine_table.mine_no}) has reported an incident in MineSpace.</p>'
Thanks, now returning the description :)

2021-10-12 14:22 UTC, areyeslo commented on services/core-api/app/api/mines/incidents/resources/mine_incidents.py
> +                incident.send_incidents_email()
Included validation through the POST method.

2021-10-12 19:02 UTC, mmumby commented on services/core-api/app/api/mines/incidents/resources/mine_incidents.py
> +
'status_code' should be getting set to 'PRE' if 'is_minespace_user'

2021-10-13 20:02 UTC, areyeslo commented on services/core-api/app/api/mines/incidents/resources/mine_incidents.py
> +
Done.

2021-10-13 22:37 UTC, mmumby commented on services/minespace-web/common/utils/helpers.js
> +  }
this is not how const are defined in JS. 


```
export const formatBooleanToString = (value, defaultValue) => {
let response;
  if (isNil(value)) {
   response = defaultValue;
  } else {
    response = value ? "Yes" : "No";
  }
  return response;
};

```

2021-10-13 22:56 UTC, areyeslo commented on services/minespace-web/common/utils/helpers.js
> +  }
My bad. Apologies for that.

2021-10-13 23:06 UTC, mmumby approved these changes
Well done, Arturo! 🔥

2021-10-13 23:18 UTC, merged