MDS-4072: Populate dropdown list project leads
bcgov/mds pull request #1952
Opened 2022-01-13 22:39 UTC by areyeslo

# Main

- Implement the configuration to assign project leads in party component.

# Other

- Seeded data to add all project leads provided in ticket.
- Added project leads to static data.

# How to test

- Create a user.

Access Project Lead user:
- When selecting the user, you can see Project Lead as a Role and an open ending date .
- Click on Update Contact button at the top right corner.

Deactivate Project Lead role:
- Fill the required data and disable the Project Lead role for the user.
- In history, the user with Project Lead role has an ending date of today.

Reactivate Project Lead role:
- Update again the user to activate the Project Lead role and set the start date to today.
- The user gets the Project Lead role activated again.

Assign Inspector role:
- Update the user to activate the Inspector role and set the start date to today
- The user gets both roles: Project Lead and Inspector

# Notes
https://bcmines.atlassian.net/browse/MDS-4072

2022-01-23 22:06 UTC, JustinMacaulay reviewed
Just a few comments

2022-01-23 22:06 UTC, JustinMacaulay commented on services/core-api/app/api/mines/variances/resources/variance.py
> +            inspector = Party.find_inspector_by_party_guid(inspector_party_guid)
wondering why this change was needed?

2022-01-23 22:06 UTC, JustinMacaulay commented on services/core-api/app/api/parties/party/models/party.py
> +    @classmethod
was there a performance concern on the find party by guid?

2022-01-23 22:06 UTC, JustinMacaulay commented on services/core-api/app/api/parties/party_appt/models/party_business_role_appt.py
> +    def get_current_business_appointments(cls, party_guid, party_business_role_code):
Is this method being used anywhere I couldn't find a reference to it.

2022-01-23 22:06 UTC, JustinMacaulay commented on services/core-web/src/components/Home.js
> +    console.log(this.props.fetchProjectLeads);
is this a forgotten log statement?

2022-01-24 19:17 UTC, areyeslo commented on services/core-api/app/api/mines/variances/resources/variance.py
> +            inspector = Party.find_inspector_by_party_guid(inspector_party_guid)
Even thought the inspecto_party_guid was passed, I considered that we needed to validate the party_guid is in fact an Inspector.

2022-01-24 19:18 UTC, areyeslo commented on services/core-api/app/api/parties/party/models/party.py
> +    @classmethod
Just to confirm the party is an Inspector.

2022-01-24 19:21 UTC, areyeslo commented on services/core-api/app/api/parties/party_appt/models/party_business_role_appt.py
> +    def get_current_business_appointments(cls, party_guid, party_business_role_code):
it is used in party_resource.py when getting the business_roles:
```
 business_roles = PartyBusinessRoleAppointment.get_current_business_appointments(
                existing_party.party_guid, ("INS", "PRL"))
```

2022-01-24 19:22 UTC, areyeslo commented on services/core-web/src/components/Home.js
> +    console.log(this.props.fetchProjectLeads);
Thanks Justin

2022-01-25 16:35 UTC, mmumby commented on services/core-web/common/reducers/partiesReducer.js
> +      };
This should be camelCase - 'projectLeads', and it should be initiated in the initialState as well

2022-01-25 16:36 UTC, mmumby commented on services/core-web/common/reducers/partiesReducer.js
'getProjectLeadsList' should be in the selector, but I see that Inspectors is also incorrectly transformed here. We should be importing all redux data into components via selectors, not reducers.

2022-01-25 16:38 UTC, mmumby requested changes, later dismissed
Please create tests for all new selectors and actionCreators.

2022-01-25 17:05 UTC, areyeslo commented on services/core-web/common/reducers/partiesReducer.js
> +      };
Agreed. Changing to camelCase.

2022-01-26 16:36 UTC, mmumby commented on services/minespace-web/common/constants/strings.js
>    none: "NO",
I don't think this needs to be here - This is for incidents and they do not have a projectLead, only Inspectors.

2022-01-26 19:25 UTC, mmumby reviewed
Great work, Happy to Approve if @JustinMacaulay is also good with his comments.

2022-01-26 21:09 UTC, JustinMacaulay approved these changes
Looks good and happy to approve with @mmumby comment

2022-01-26 22:38 UTC, merged