[MDS-5345] Fix error while uploading document.
bcgov/mds pull request #2564
Opened 2023-06-15 22:56 UTC by henryoforeh-aot

## Objective 

[MDS-5345](https://bcmines.atlassian.net/browse/MDS-5345)

- Fixed a bug linked to uploading a document. This bug was caused by sending undefined/null **mines_guid**  as a query parameter to the project summary document upload end point.

![image](https://github.com/bcgov/mds/assets/72251620/5d8866ff-f195-4bcd-8466-c041e24029ad)

2023-06-16 19:36 UTC, taraepp approved these changes
LGTM

2023-06-16 19:37 UTC, taraepp requested changes
Wait one thing- can we make sure the swagger is updated on the BE to reflect that the mine_guid is required?

2023-06-19 17:07 UTC, simensma-fresh approved these changes

2023-06-19 18:25 UTC, taraepp approved these changes

2023-06-19 18:57 UTC, merged