[MDS-5272] bulk file zipping
bcgov/mds pull request #2594
Opened 2023-07-20 17:15 UTC by matbusby-fw

## Objective 

- Allow the zipping of multiple files that exist in our storage,
- create a progress monitoring endpoint for the front end to poll
- upload the new zipped document to the object store and return a guid for it once the process is complete
- The endpoint for creating a zip accepts an array of document guids and an optional file name for the zipped file.  If there is no file name, it currently defaults to the mine number and a timestamp.
- This maintains the pretty path file structure for the documents within the zip file
- Zips are added to their own base directory - "zipped_docs"
  - Currently there is no exipiry set on this directory, but eventually we want to add one.

Zip documents endpoint -> `{{baseUrl}}/mines/{{mine_guid}}/documents/zip`
Zip progress endpoint -> `{{baseUrl}}/mines/documents/zip/{{task_id}}`

[MDS-5272](https://bcmines.atlassian.net/browse/MDS-5272)

_Why are you making this change? Provide a short explanation and/or screenshots_

2023-07-20 19:41 UTC, henryoforeh-aot approved these changes

2023-07-21 16:11 UTC, simensma-fresh requested changes
Overall looks good!

Are you able to add the new endpoints to tests/auth/test_expected_auth? Would be good to have as many endpoints as we can covered there.

Only concern would be that we're keeping the fully zipped file in memory before uploading it back to S3, which might cause some memory issues when running in Openshift when zipping many/large. However I'm happy to revisit later if it becomes an issue during testing

2023-07-21 16:11 UTC, simensma-fresh commented on services/document-manager/backend/app/docman/resources/document.py
> +        response.autocorrect_location_header = False
Think all of these are covered in the `initiate_document_upload` func, so probably not needed here

2023-07-21 16:17 UTC, matbusby-fw commented on services/document-manager/backend/app/docman/resources/document.py
> +        response.autocorrect_location_header = False
Hmmm, this is odd.  These lines came up during my rebase.  There weren't something I added.  I'm not sure why they are being flagged as new.  I'll double check the existing code to see if I can figure out where they came from.

2023-07-21 17:18 UTC, asinn134 approved these changes
Nice work!

2023-07-25 21:48 UTC, simensma-fresh approved these changes

2023-07-25 21:49 UTC, merged