[MDS-5410] Minespace Management Button (#2622)
bcgov/mds pull request #2623
Opened 2023-08-10 16:11 UTC by taraepp

## Objective 
- make admin navigation (verified mines, minespace management) visible on admin dashboard again
   - added "exact" attribute back
- updated nvmrc with new node version, and added yarn install, nvm install to restart_codespaces script
- cleaned up some minor issues that generate a lot of console errors: 
   - added key for iterator, 
   - and updated AdminNavigation to functional+TS, and to use _items_ instead of _children_
      - the items vs children issue is to eventually be ready for new version of antd, and is for Menu components as well as I believe Tabs/TabPane, possibly a couple of others
      - changing this also got rid of a bunch of "warnKey"/"eventKey" messages- it seems that antd uses those internally when it catches that you're using children, but React flags it as an invalid attribute. 
      - changing from children to items also made antd generate different classnames or DOM structures and so new style file to deal with these changes. There were some conflicts with our existing rules, so notes added with the intention of us eventually removing the old styles

[MDS-5410](https://bcmines.atlassian.net/browse/MDS-5410)

_Why are you making this change? Provide a short explanation and/or screenshots_

2023-08-10 16:14 UTC, simensma-fresh submitted a review, later dismissed

2023-08-11 15:00 UTC, henryoforeh-aot commented on services/core-web/src/components/admin/AdminNavigation.tsx
> +};
Is it possible to rewrite this to be more "typescriptish"? 

const propTypes = {
  activeButton: string,
  openSubMenuKey: Array<string>,
};

2023-08-11 15:18 UTC, henryoforeh-aot submitted a review, later dismissed
Nice work! I just had one minor comment.

2023-08-11 16:04 UTC, matbusby-fw commented on services/core-web/src/components/admin/AdminNavigation.tsx
> +};
I'm in favour of actually ditching propTypes in favour of interfaces

interface AdminNavigationProps {
activeButton: string,
openSubMenuKey: string[]
}

And then `export const AdminNavigation: FC<AdminNavigationProps>`

That's my preference, but either way works.

2023-08-11 16:07 UTC, matbusby-fw requested changes
Yay!  Happy to have this back, and YAY Typescript conversions!

I like Henry's suggestion to make the one file more Typescripty by changing the PropTypes.  Not a hill to die on for me though if you prefer this pattern.

2023-08-11 17:55 UTC, henryoforeh-aot submitted a review, later dismissed

2023-08-11 17:58 UTC, matbusby-fw commented on services/core-web/src/components/admin/AdminNavigation.tsx
> +const AdminNavigation: FC<AdminNavigationProps> = (props: AdminNavigationProps) => {
FYI, once the FC<AdminNavigationProps> is there, it will infer the propType for props without explicitly typing it.

2023-08-11 18:51 UTC, henryoforeh-aot approved these changes

2023-08-11 18:52 UTC, matbusby-fw approved these changes

2023-08-11 18:54 UTC, merged