[MDS-5397] cypress major projects description
bcgov/mds pull request #2846
Opened 2023-12-11 19:52 UTC by henryoforeh-aot

## Objective 

[MDS-5397](https://bcmines.atlassian.net/browse/MDS-5397)

Implemented cypress test to create a new project.

2023-12-11 20:05 UTC, simensma-fresh requested changes

2023-12-11 20:05 UTC, simensma-fresh commented on services/core-web/cypress/e2e/majorprojects.cy.ts
> +    }).as("createNewProject");
I'm wondering if we maybe could maybe not stub the response here? In the end we would also want to know if the backend is working or not

2023-12-11 20:05 UTC, simensma-fresh commented on services/core-web/cypress/e2e/majorprojects.cy.ts
> +    });
Could we add in a step here to navigate back to the Permits and Approvals tab and check if the new one shows up in the table?

2023-12-13 16:13 UTC, simensma-fresh approved these changes

2023-12-13 16:45 UTC, matbusby-fw approved these changes
🙌🏻

2023-12-13 16:46 UTC, merged