[MDS-5836] trigger notification report requested
bcgov/mds pull request #3087
Opened 2024-05-08 00:09 UTC by isuru-aot

## Objective 

[MDS-5836](https://bcmines.atlassian.net/browse/MDS-5836)

_Why are you making this change? Provide a short explanation and/or screenshots_
![Screenshot 2024-05-07 165735](https://github.com/bcgov/mds/assets/118843449/1e7460b5-f744-46df-a8b0-53e0316ad513)
![Screenshot 2024-05-07 165749](https://github.com/bcgov/mds/assets/118843449/e03b45dc-0d65-4317-b374-fa5b75df2065)

2024-05-08 14:18 UTC, henryoforeh-aot submitted a review, later dismissed

2024-05-08 17:36 UTC, matbusby-fw commented on services/core-api/app/api/mines/reports/models/mine_report.py
> +            due_date = due_date = (self.due_date).strftime("%b %d %Y") if self.due_date else "N/A"
```suggestion
            due_date = (self.due_date).strftime("%b %d %Y") if self.due_date else "N/A"
```

2024-05-08 17:38 UTC, matbusby-fw requested changes
Awesome work!  Just noticed one double assignment of a due date in there.

2024-05-10 17:08 UTC, asinn134 approved these changes

2024-05-10 17:15 UTC, henryoforeh-aot approved these changes

2024-05-10 17:29 UTC, isuru-aot commented on services/core-api/app/api/mines/reports/models/mine_report.py
> +            due_date = due_date = (self.due_date).strftime("%b %d %Y") if self.due_date else "N/A"
@matbusby-fw need your approval again for this.

2024-05-10 18:06 UTC, matbusby-fw approved these changes

2024-05-10 18:07 UTC, merged