[MDS-5813] [MDS-5791] File Upload Bug fix and some improvements
bcgov/mds pull request #3094
Opened 2024-05-09 23:03 UTC by isuru-aot

## Objective 

[MDS-5791](https://bcmines.atlassian.net/browse/MDS-5791)

_Why are you making this change? Provide a short explanation and/or screenshots_
Bug is fixed with some other improvements.

2024-05-10 16:37 UTC, henryoforeh-aot commented on services/minespace-web/src/components/pages/Project/ProjectSummaryPage.tsx
> +          change(
Dispatch also needs to happen here. Code on line 281 is not required.

2024-05-10 18:09 UTC, matbusby-fw commented on services/common/src/components/projectSummary/AuthorizationsInvolved.tsx
> +    ...props.formValues.authorizations[code],
Should this change include the `AMENDMENT[0]` as it did before?

```suggestion
    ...props.formValues.authorizations[code].AMENDMENT[0],
```

2024-05-10 18:12 UTC, matbusby-fw requested changes
I think it's looking mostly good.  Just what Henry mentioned and one small change to keep it inline with the previous functionality.

2024-05-11 04:14 UTC, isuru-aot commented
Removed the `dispatch(change(....` and moved the logic to BE.

2024-05-13 16:38 UTC, henryoforeh-aot commented on services/core-api/app/api/projects/project_summary/models/project_summary.py
> +                            print("----mine_document_guid: ", doc.get('mine_document_guid'))
Do you still need the print statements here ?

2024-05-13 16:58 UTC, asinn134 approved these changes

2024-05-13 17:01 UTC, henryoforeh-aot approved these changes

2024-05-13 17:26 UTC, matbusby-fw approved these changes

2024-05-13 17:27 UTC, merged