[MDS-6074] - BE spatial bugfixes
bcgov/mds pull request #3184
Opened 2024-07-12 17:56 UTC by matbusby-fw

- Changed bundle_id column in mine_document_bundle to a serial from a guid
- A few other updates to the mine_document_bundle table- Added a mine_document_bundle and mine_document_bundle_id to the mine_document model
- Add response a response model for mine_document_bundle and included it in the mine_document response model

Note: The response is currently not marshalling properly (returning null values). I'm splitting that out as a separate bug in order to get the other fixes live now.

2024-07-12 21:28 UTC, simensma-fresh requested changes

2024-07-12 21:28 UTC, simensma-fresh commented on services/document-manager/backend/app/__init__.py
> +        os.makedirs('/tmp/spatial')
![image](https://github.com/user-attachments/assets/88a73ee7-2ffe-4d01-bdfa-ad7ed65a984a)
Looks like this doesn't match exactly with the path the files are downloaded to?
Think we might need to add a leading `/` there

2024-07-15 16:38 UTC, simensma-fresh submitted a review, later dismissed

2024-07-16 15:29 UTC, henryoforeh-dev submitted a review, later dismissed

2024-07-16 15:41 UTC, taraepp commented on services/core-api/app/api/mines/response_models.py
> +        'mine_document_bundle': fields.Nested(MINE_DOCUMENT_BUNDLE_MODEL),
I can see sending back the geomark_id, but I don't think any of the other fields are going to be used at all on the FE. I think I'd still rather do a fetch to get the geomark_id, as it's only used when we're displaying that particular bundle (one at a time).

2024-07-17 15:12 UTC, simensma-fresh approved these changes

2024-07-17 16:38 UTC, taraepp approved these changes

2024-07-17 16:49 UTC, merged