[MDS-6024] Fix issues on all documents
bcgov/mds pull request #3202
Opened 2024-07-31 17:15 UTC by henryoforeh-dev

## Objective 

[MDS-6024](https://bcmines.atlassian.net/browse/MDS-6024)

_Why are you making this change? Provide a short explanation and/or screenshots_

1. Fixed issue with displaying archived files.
2. Fixed issue on ReplaceDocumentModal component.
3. Updated unit tests and snapshot test.

2024-07-31 18:06 UTC, simensma-fresh requested changes

2024-07-31 18:06 UTC, simensma-fresh commented on services/core-web/src/tests/components/modalContent/__snapshots__/ReplaceDocumentModal.spec.tsx.snap
> +exports[`ReplaceDocumentModal renders properly 1`] = `undefined`;
Would be good to have this snapshot render properly instead of being `undefined` if possible

2024-07-31 19:13 UTC, henryoforeh-dev commented on services/core-web/src/tests/components/modalContent/__snapshots__/ReplaceDocumentModal.spec.tsx.snap
> +exports[`ReplaceDocumentModal renders properly 1`] = `undefined`;
Updated

2024-07-31 19:41 UTC, taraepp commented on services/common/src/components/documents/ReplaceDocumentModal.tsx
> +      <Field
thanks, this was driving me _nuts._

2024-07-31 19:42 UTC, taraepp commented on services/common/src/components/projects/ProjectDocumentsTab.tsx
>          })
So, I tried doing this, and as I recall, it would give me _all_ of the mine's archived documents, and not filtered to the project. Are you 100% sure that we're not getting unrelated documents here? I think we just need to add a join to the ams docs table on the BE.

2024-07-31 19:43 UTC, taraepp commented on services/core-web/src/tests/components/modalContent/ReplaceDocumentModal.spec.tsx
> +  it("renders correctly and matches the snapshot", () => {
I am wondering why go back to the "shallow" render when the react-testing-library render gave us a better snapshot.

2024-08-01 15:58 UTC, simensma-fresh approved these changes

2024-08-01 21:40 UTC, taraepp approved these changes

2024-08-01 23:09 UTC, merged