[MDS-5986] reject multiple connections acceptance
bcgov/mds pull request #3204
Opened 2024-08-02 18:00 UTC by Jsyro

## Objective 

[MDS-5986](https://bcmines.atlassian.net/browse/MDS-5986)

unexpected breaking issue.

2024-08-02 18:55 UTC, henryoforeh-dev submitted a review, later dismissed

2024-08-06 20:25 UTC, henryoforeh-dev approved these changes

2024-08-07 15:55 UTC, matbusby-fw approved these changes

2024-08-07 23:17 UTC, simensma-fresh requested changes
We merged a fix for the `docker-compose` command not found error that causes the backend tests to fail if you're able to rebase your branch on top of the dev branch

2024-08-09 17:12 UTC, simensma-fresh approved these changes

2024-08-12 15:48 UTC, merged