[MDS-6011] Fix buttons in modal footers, only show allowed type in replace modal
bcgov/mds pull request #3220
Opened 2024-08-16 20:50 UTC by taraepp

## Objective 
- this, along with prev PR should deal with _most_ button styling issues on CORE
   - specifically targeting buttons here in "ant-modal-footer" to add margins
- only show the matching file type in replace modal
- did a little cleaning of doc modals
   - switched to hooks
   - removed props like "openModal" from DocumentTableProps
   - added snapshot tests where missing
   - used FormWrapper so submit button can disable itself when submitting
   - cleaned up some async stuff: adjusted the prop to -> Promise<void>, put in awaits & Promise.all
   - noticed an issue with bulk actions vs actions on individual documents where we were allowing bulk archive after disallowing individual archive. Brought them in line. 

[MDS-6011](https://bcmines.atlassian.net/browse/MDS-6011)

_Why are you making this change? Provide a short explanation and/or screenshots_
![image](https://github.com/user-attachments/assets/1c8c527d-d2dd-44cd-8b15-a59036ca9854)

2024-08-19 15:48 UTC, simensma-fresh approved these changes

2024-08-19 16:31 UTC, simensma-fresh requested changes
Looks like cypress tests + common package tests are failing. Otherwise looks good

2024-08-19 23:02 UTC, taraepp commented on services/core-web/src/styles/settings/themeOverride.scss
> +  margin: 10px;
A note for the future:

Writing it nested like:
`.ant-modal-footer { .ant-btn { margin: 10px }}`
did produce a build error in the javascript bundle. In order to reproduce the bundle error, just change it back to nested.

However, leaving it in, and adding `.ant-modal-footer .ant-btn {...` did not produce a build error. So it is not the presence or absence of that particular rule/format that breaks the build.

2024-08-20 04:18 UTC, simensma-fresh approved these changes

2024-08-20 13:47 UTC, henryoforeh-dev approved these changes

2024-08-20 15:21 UTC, merged