[MDS-6120] Add permit conditions version history
bcgov/mds pull request #3228
Opened 2024-08-26 20:08 UTC by matbusby-fw

Utilize the versioning implemention set up in Core-Api to enable versions of permit conditions.

The retrieval of versioned information is scoped to a future ticket.

## Objective 

[MDS-6120](https://bcmines.atlassian.net/browse/MDS-6120)

![permit-condition-versions](https://github.com/user-attachments/assets/624e583b-81d5-4252-a718-d5ca76caecaa)

2024-08-26 20:47 UTC, henryoforeh-dev submitted a review, later dismissed

2024-08-26 21:50 UTC, simensma-fresh requested changes
Thoughts on adding a quick test or two here? E.g. editing a permit condition and making sure the history table also gets populated.

2024-08-27 16:31 UTC, simensma-fresh approved these changes

2024-08-27 16:32 UTC, henryoforeh-dev approved these changes

2024-08-27 16:34 UTC, merged