[MDS-6082] Implement Caching.
bcgov/mds pull request #3232
Opened 2024-08-30 19:18 UTC by henryoforeh-dev

## Objective 

[MDS-6082](https://bcmines.atlassian.net/browse/MDS-6082)

_Why are you making this change? Provide a short explanation and/or screenshots_
Implemented response caching for LLM response.

2024-09-03 15:24 UTC, taraepp approved these changes, later dismissed
Interesting that I can see your added test but sonarcloud thinks there's 0% coverage (probably need to fix the configuration there in the future)

LGTM!

2024-09-03 18:53 UTC, simensma-fresh requested changes

2024-09-03 18:53 UTC, simensma-fresh commented on services/permits/app/permit_conditions/pipelines/CachedAzureOpenAIChatGenerator.py
> +                try:
Can probably get rid of the `pickle` cache now that we're using Elasticsearch

2024-09-03 19:03 UTC, matbusby-fw submitted a review, later dismissed
Once Simen's comment is resolved it looks good to me!

2024-09-03 19:22 UTC, henryoforeh-dev commented on services/permits/app/permit_conditions/pipelines/CachedAzureOpenAIChatGenerator.py
> +                try:
Updated to remove all logic related to `pickle` cache.

2024-09-03 22:22 UTC, matbusby-fw approved these changes

2024-09-04 14:09 UTC, simensma-fresh approved these changes

2024-09-04 14:29 UTC, merged