[MDS-6129] streamline status actions
bcgov/mds pull request #3245
Opened 2024-09-11 22:48 UTC by henryoforeh-dev

## Objective 

[MDS-6129](https://bcmines.atlassian.net/browse/MDS-6129)

_Why are you making this change? Provide a short explanation and/or screenshots_

Implemented logic to enable/disable fields with respect to status.

All conditions are in Miroboard link. https://miro.com/app/board/uXjVKnK62M0=/

2024-09-12 22:24 UTC, matbusby-fw commented on services/common/src/constants/utils.ts
> +  if (disabledStatuses.has(projectSummaryStatusCode)) return true;
Nice.  Don't see `.has` used too much.  Slick.

2024-09-12 22:33 UTC, matbusby-fw requested changes
Looks really nice.  My only thought is that we should probably add some snapshots for these project components (I realize for the most part you just added the disabled functionality on most of them, but maybe we could bump up the coverage a bit by adding snapshots for at least a couple of them?)

2024-09-13 15:15 UTC, henryoforeh-dev commented
> Looks really nice. My only thought is that we should probably add some snapshots for these project components (I realize for the most part you just added the disabled functionality on most of them, but maybe we could bump up the coverage a bit by adding snapshots for at least a couple of them?)

I added snapshot tests for all the components. While still short on recommended coverage, it will take more work to get each one to 80%.

2024-09-13 18:09 UTC, matbusby-fw approved these changes
Awesome!  Yeah, I think we're okay not always hitting the 80%.  Especially in cases like this where it requires new testing on previously created work.

2024-09-13 18:38 UTC, asinn134 approved these changes

2024-09-13 20:19 UTC, merged