[MDS-6207] Show PDF of permit amendment on Permit Conditions page + auto-focus on click
bcgov/mds pull request #3351
Opened 2024-12-17 00:08 UTC by simensma-fresh

## Objective 

[MDS-6207](https://bcmines.atlassian.net/browse/MDS-6207)

With all the data about a permit condition now coming over from the permit service, we now have access to the bounding box of where it came from in the original PDF. This PR adds a side-by-side view of the conditions where we highlight the condition in the original PDF on click. Note: This is behind a feature flag, and just added so we can see how well it works/ if it's worth polishing.

![image](https://github.com/user-attachments/assets/5fd8ff14-cd07-4f49-b1ed-f8ce9afd14dc)

2024-12-17 18:25 UTC, taraepp commented on services/core-web/src/tests/components/mine/Permit/PreviewPermitAmendmentDocument.spec.tsx
> +    meta: {
I get a TS error about the type on meta- looks like it's missing 'role'?

2024-12-17 20:02 UTC, taraepp commented on services/common/src/redux/slices/permitServiceSlice.ts
> +  permit_amendment_document_guid: string;
this bit makes a TS error on line 148 (where it fetches task status). Should the permit_amendment_document_guid be optional? Either that or it wants to be set to a value on that line (which probably doesn't make sense)

2024-12-17 20:18 UTC, taraepp commented
Other than some TS issues, looks very cool and works well!

2024-12-18 18:27 UTC, matbusby-fw commented on services/common/src/components/syncfusion/DocumentViewer.tsx
> +      id={id || "pdfviewer-container"}
Could probably remove the "pdfviewer-container" part here since it's set as a default in the props.

2024-12-18 18:32 UTC, matbusby-fw commented on services/common/src/interfaces/permits/permitCondition.interface.ts
> +export interface IPermitConditionCategory {
Oh, I think this already exists lower in this file.

2024-12-18 18:37 UTC, matbusby-fw requested changes
Looks awesome!  

Just noticed a duplicated interface and a suggestion on removing an unnecessary `||` block.

2024-12-18 18:44 UTC, simensma-fresh commented
@matbusby-fw Fixed 👍

2024-12-18 19:53 UTC, taraepp approved these changes

2024-12-18 19:56 UTC, matbusby-fw approved these changes

2024-12-18 20:06 UTC, asinn134 approved these changes

2024-12-18 21:58 UTC, merged