[MDS-6304] Tighten up Archive/Replace docs for Major Mine Application
bcgov/mds pull request #3352
Opened 2024-12-18 19:46 UTC by taraepp

## Objective 
- don't allow replace on spatial table
- lock down actions on the form according to status instead of assuming they can't navigate to it
- removed some unused imports
- made a couple little tweaks to the document table...
   - I thought it would show Download instead of Actions so I added another condition to the logic to make it so
   - in order to put the header in a row with the Actions/Download button, passed it as a param
   - and then added spacing between the button and the table (on MS only. I seem to recall it already has spacing on CORE)

[MDS-6304](https://bcmines.atlassian.net/browse/MDS-6304)

_Why are you making this change? Provide a short explanation and/or screenshots_
![image](https://github.com/user-attachments/assets/a0992603-051e-4050-aac4-50110aecb7ef)

2024-12-18 20:39 UTC, sggerard submitted a review, later dismissed

2024-12-18 22:09 UTC, asinn134 approved these changes, later dismissed

2024-12-18 22:43 UTC, simensma-fresh requested changes
Looks like there's a merge conflict, might have to re-generate that snap. Otherwise looks good!

2024-12-19 16:46 UTC, simensma-fresh approved these changes

2024-12-19 17:35 UTC, asinn134 approved these changes

2024-12-19 17:38 UTC, sggerard approved these changes

2024-12-19 19:06 UTC, merged