[MDS-6306] Fix minespace user mine management
bcgov/mds pull request #3358
Opened 2024-12-27 20:13 UTC by sggerard

## Objective 

[MDS-](https://bcmines.atlassian.net/browse/MDS-6306)

As a core Administrator, it is hard to edit a minespace user's list of mines due to the mine guid showing instead of the mine name. This is due to only the first 50 mines being returned by the api instead of the complete list which would cause a large slow response.

As an alternative solution, I have added all the mines that user's currently have assigned to the list so that they show correctly. Additionally I have converted files to typescript, fixed a bug where an update would trigger a call multiple times and sorted the list of mines.

2025-01-06 15:47 UTC, simensma-fresh requested changes
Yay for more js->ts conversion!

2025-01-06 15:47 UTC, simensma-fresh commented on services/core-web/src/components/Forms/EditMinespaceUser.tsx
> +import { IMine } from "@mds/common";
Could we import this from `@mds/common/interfaces` instead? Hoping to get rid of that root global export

2025-01-06 15:47 UTC, simensma-fresh commented on services/core-web/src/components/common/RenderMultiSelect.tsx
> +import { IOption } from "@mds/common";
Could we import this from `@mds/common/interfaces` instead?

2025-01-06 17:58 UTC, simensma-fresh submitted a review, later dismissed

2025-01-07 17:40 UTC, simensma-fresh approved these changes

2025-01-07 17:58 UTC, taraepp commented on services/core-web/src/components/common/RenderMultiSelect.tsx
> +import React, { FC, useRef } from "react";
Would say just skip updating the core-web MultiSelect. (I deleted it on my branch already). Use common version instead.

2025-01-08 18:10 UTC, asinn134 approved these changes

2025-01-08 19:52 UTC, merged